name: shopin_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  adaptive_theme: ^3.2.0
  hexcolor: ^3.0.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  firebase_analytics: ^10.2.1
  cloud_functions: ^4.1.1
  snackbar: ^1.0.2
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  flutter_material_pickers: ^3.3.0
  bottom_navy_bar: ^6.0.0
  image_picker: ^0.8.7+4
  badges: ^3.1.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#f8f8f8"
  adaptive_icon_foreground: "dev_assets/logo_adaptive.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/about.png
    - images/featured/camera.jpg
    - images/featured/man.jpg
    - images/featured/woman.jpg
    - images/category/dress.png
    - images/userImage.png
    - images/shopping.png
    - dev_assets/logo.png
    - dev_assets/logo_adaptive.png
    - animations/login/login-successful-splash.gif
    - animations/sign up/signup-successful-splash.gif
    - animations/successful/successfully-green.gif
    - images/login/frame-1.png
    - images/login/frame-2.png
    - images/signup/frame-1.png
    - images/signup/frame-2.png

    # - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
